# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwRQrG7INy36aGiNDzXTG9zF7RG4Abmk
"""

!pip install -q langchain langchain-community langchain-groq faiss-cpu sentence-transformers python-docx gradio

from google.colab import files
uploaded = files.upload()

!pip install -q langchain==0.2.11 langchain-community langchain-groq faiss-cpu sentence-transformers gradio python-docx

!pip install -q --upgrade pip

!pip install -q \
langchain==0.2.11 \
langchain-community \
langchain-text-splitters \
langchain-groq \
faiss-cpu \
sentence-transformers \
gradio \
python-docx

import os
from docx import Document

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_groq import ChatGroq

from langchain.chains.retrieval_qa.base import RetrievalQA
import gradio as gr

# =========================
# API KEY (ADD LATER)
# =========================
os.environ["GROQ_API_KEY"] = "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"

# =========================
# LOAD DOCX
# =========================
def load_docx(file_path):
    doc = Document(file_path)
    text = ""
    for para in doc.paragraphs:
        if para.text.strip():
            text += para.text.strip() + "\n"
    return text

doc_text = load_docx("fashion_chatbotdata.docx")

# =========================
# SPLIT TEXT
# =========================
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = splitter.split_text(doc_text)

# =========================
# EMBEDDINGS + VECTOR DB
# =========================
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_texts(chunks, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

# =========================
# GROQ LLM
# =========================
llm = ChatGroq(
    groq_api_key=os.environ["GROQ_API_KEY"],
    model_name="llama-3.1-8b-instant"
)

# =========================
# RAG CHAIN
# =========================
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff"
)

# =========================
# CHAT FUNCTION
# =========================
def chat(user_message):
    if not user_message:
        return "Please ask a question."

    try:
        response = qa_chain.invoke({"query": user_message})
        return response["result"]

    except Exception as e:
        return f"Error: {str(e)}"

# =========================
# GRADIO UI
# =========================
interface = gr.Interface(
    fn=chat,
    inputs=gr.Textbox(lines=2, placeholder="Ask your fashion question..."),
    outputs="text",
    title="👗 PakStyle AI RAG Chatbot",
    description="Fashion Recommendation Chatbot using DOCX + FAISS + Groq Llama3"
)

interface.launch()

